framework:
  secret: "%env(APP_SECRET)%"
  http_method_override: false
  handle_all_throwables: true

  messenger:
    transports:
      async: "%env(MESSENGER_TRANSPORT_DSN)%"

  php_errors:
    log: true

  session:
    enabled: false
