#!/bin/sh
set -e

echo "=== Notification Service: Waiting for MySQL ==="
DB_URL="${DATABASE_URL:-mysql://app:secret@mysql:3306/notifications}"
DB_HOST=$(echo "$DB_URL" | sed -E 's|.*@([^:/]+).*|\1|')
DB_PORT=$(echo "$DB_URL" | sed -E 's|.*:([0-9]+)/.*|\1|')
DB_NAME=$(echo "$DB_URL" | sed -E 's|.*/([^?]+).*|\1|')
DB_USER=$(echo "$DB_URL" | sed -E 's|.*://([^:]+):.*|\1|')
DB_PASS=$(echo "$DB_URL" | sed -E 's|.*://[^:]+:([^@]+)@.*|\1|')
until php -r "new PDO('mysql:host=${DB_HOST};port=${DB_PORT};dbname=${DB_NAME}', '${DB_USER}', '${DB_PASS}');" 2>/dev/null; do
    echo "  MySQL (${DB_NAME}) not ready, retrying in 2s..."
    sleep 2
done
echo "=== MySQL (${DB_NAME}) is ready ==="

# ── Wait for JWT public key from auth-service ───────────────
echo "=== Waiting for JWT public key (generated by auth-service) ==="
while [ ! -f /app/config/jwt/public.pem ]; do
    echo "  JWT public key not yet available, retrying in 2s..."
    sleep 2
done
echo "=== JWT public key found ==="

cd /app

# ── Composer ────────────────────────────────────────────────
if [ ! -d vendor ] || [ ! -f vendor/autoload.php ]; then
    echo "Installing dependencies..."
    composer install --no-interaction --optimize-autoloader || true
else
    composer update --no-interaction 2>/dev/null || true
fi

# ── Migrations & Cache ─────────────────────────────────────
php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
php bin/console cache:clear || true

echo "=== Notification Service is ready ==="
exec "$@"
