services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Service\RequestAccessTemplateUpdater:
    arguments:
      $channelUpdaters:
        - '@App\Service\TemplateUpdate\InboxTemplateChannelUpdater'
        - '@App\Service\TemplateUpdate\EmailTemplateChannelUpdater'
        - '@App\Service\TemplateUpdate\PushTemplateChannelUpdater'
